# Generated by Django 3.0.4 on 2020-03-29 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200328_1202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
